#!/bin/bash

# Copyright (c) 2012 NTT DOCOMO, INC. 
# Copyright 2012 Hewlett-Packard Development Company, L.P.
# Copyright 2013 National Institute of Informatics.
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

echo "init"

source /init-func

PATH=/sbin:/bin:/usr/bin:/usr/sbin
export PATH

mkdir -p /proc
mkdir -p /sys
mkdir -p /dev
mkdir -p /boot
mkdir -p /etc
mkdir -p /mnt
mkdir -p /lib/modules
mkdir -p /etc/mtab

mount -t proc proc /proc

mount -t sysfs none /sys
mount -t tmpfs none /dev
ln -sf /proc/self/fd /dev/fd
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/tty0 c 4 0
mknod /dev/tty1 c 4 1
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3
mknod /dev/tty4 c 4 4
mknod /dev/tty5 c 4 5
mknod /dev/tty6 c 4 6
mknod /dev/tty7 c 4 7
mknod /dev/tty8 c 4 8
mknod /dev/tty9 c 4 9
mknod /dev/tty c 5 0
mknod -m 0600 /dev/console c 5 1
mknod -m 0666 /dev/ptmx c 5 2
mkdir -p /dev/.udev
mkdir -p /dev/.udev/data

echo "starting syslogd"

echo '*.* /initlog' > /etc/syslog.conf
syslogd
klogd

echo "starting udevd"
udevd --daemon --resolve-names=never

echo "load modules"
load_modules_by_udev

if [ -n "$prov_mac_address" -a -n "$prov_ip_address" -a -n "$prov_subnet" ]; then
    echo "starting network $prov_mac_address"

    nic=`ifconfig -a | grep -i $prov_mac_address | awk '{print $1}'`

    if [ -z "$nic" ]; then
        echo "could not find an interface owns MAC=$prov_mac_address"
		echo "Starting troubleshooting shell."
		bash
	fi

    ifconfig lo 127.0.0.1 up
    ifconfig "$nic" up
    ip addr add $prov_ip_address/$prov_subnet dev $nic

    rsync_ip=$(echo "$ami_path" | cut -d'/' -f 3)
    rsync_ip=$(echo "$rsync_ip" | cut -d':' -f 1)
    w=10

while [ $w -gt 0 ]; do
        ping -c 5 $rsync_ip > /dev/null
	if [ $? -eq 0 ]; then
		break
	fi
        sleep 5
        w=`expr $w - 1`
        if [ $w -eq 0 ]; then
            echo "ERROR:not connect rsync_ip"
            echo "Starting troubleshooting shell."
            bash
        fi
done
    echo "network for ready"
else
    echo "don't have addr ip address param"
fi

if [ $action == "delete" ]; then
    rcync_cmd=$(echo "$ami_path" | cut -d'/' -f 1-3)
    rsync -HSa $rcync_cmd/$deletion_scripts_path /etc/scripts/
    if [ -e /etc/scripts/deletion-scripts ]; then
        echo "deletion-scripts start"
        bash /etc/scripts/deletion-scripts
    else
        echo "disk-clean start"
        bash /etc/scripts/disk-clean.sh
    fi
    echo "delete complete"
else
    echo "deploy start"
    bash /etc/scripts/ami-deploy.sh
    echo "deploy complete"
fi

bash

